apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginy
  labels:
    app: nginy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginy
  template:
    metadata:
      labels:
        app: nginy
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80